In [60]:
import numpy as np#importing numpy

In [61]:
np1 = np.array([1,2,3,4,5]) #creating numpy array
np1

array([1, 2, 3, 4, 5])

In [9]:
np2=np.array([[2,3],[3,4],[5,6]])
np2

array([[2, 3],
       [3, 4],
       [5, 6]])

In [12]:
np3=np.array([2,3].[4,6])
print(np3,end=" ")

SyntaxError: invalid syntax (64784819.py, line 1)

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(2,10,3)

array([2, 5, 8])

In [31]:
np.empty(2)

array([1., 1.])

In [17]:
np.ones(2)

array([1., 1.])

In [22]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
 arr=np.array([2,3,5,4,7])
np.sort(arr)

array([2, 3, 4, 5, 7])

In [29]:
type(arr)

numpy.ndarray

In [34]:
np1=np.array([2,3,4,5])
np2=np.array([6,7,8,7])
np.concatenate((np1,np2))

array([2, 3, 4, 5, 6, 7, 8, 7])

In [41]:
np1=np.array([[2,3],[4,5]])
np2=np.array([[6,7,]])
np.concatenate((np1,np2), axis=0)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [43]:
np1=np.array([[[2,3,4],[2,6,7]]])
np2=np.array([[[3,5,7],[3,5,8,]]])
np3=np.array([[[4,6,8],[5,7,0]]])
np1=np.concatenate(((np1,np2,np3)))

array([[[2, 3, 4],
        [2, 6, 7]],

       [[3, 5, 7],
        [3, 5, 8]],

       [[4, 6, 8],
        [5, 7, 0]]])

In [48]:
np1.size

6

In [49]:
np1=np.array([[[2, 3, 4],
        [2, 6, 7]],

       [[3, 5, 7],
        [3, 5, 8]],

       [[4, 6, 8],
        [5, 7, 0]]])
np1.ndim

3

In [57]:
np1=np.array([[[2, 3, 4],
        [2, 6, 7]],

       [[3, 5, 7],
        [3, 5, 8]],

       [[4, 6, 8],
        [5, 7, 0]]])


In [58]:
print(np1.reshape(6,4))

ValueError: cannot reshape array of size 18 into shape (6,4)

In [59]:
arr=np.array([[2,4,5],[6,3,1]])
np.save('filename',arr)
np.load('filename.npy')
arr

array([[2, 4, 5],
       [6, 3, 1]])

In [8]:
import pandas as pd
import numpy as np

In [10]:
arr=np.array([[2,3],[5,6]])
arr

array([[2, 3],
       [5, 6]])

In [13]:
df=pd.DataFrame(arr)
df

0  1
0  2  3
1  5  6

In [15]:
df.to_csv("data.csv")

In [16]:
data=pd.read_csv("data.csv")
data

Unnamed: 0  0  1
0           0  2  3
1           1  5  6